### ISSUE TITLE
NPE when running the script

### ISSUE THREAD

**Issue by mstahv** [vaadin/framework8-migration-tool#9]
rmb-2:addon-test-helpers }> java -jar ~/Downloads/framework8-migration-tool-8.0-SNAPSHOT.jar 
Scanning for compatibility classes for 8.0.0.beta1 version...
Downloading vaadin-compatibility-server 8.0.0.beta1 from Maven to /opt/local/share/java/maven3/repository
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NullPointerException
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:361)
	at com.vaadin.framework8.migrate.MavenResolver.resolve(MavenResolver.java:68)
	at com.vaadin.framework8.migrate.VadinJarFinder.download(VadinJarFinder.java:55)
	at com.vaadin.framework8.migrate.VadinJarFinder.lambda$get$1(VadinJarFinder.java:22)
	at java.util.Optional.orElseGet(Optional.java:267)
	at com.vaadin.framework8.migrate.VadinJarFinder.get(VadinJarFinder.java:22)
	at com.vaadin.framework8.migrate.Migrate.main(Migrate.java:38)

**Comment by ahoehma** [comment]
Same here for my try ...

hoehmann@XXXX MINGW64 /d/dev/git/coc/goos-experiments (feature/OWN-121_Lets_try_Vaadin8)
$ java -jar "D:/Dev/ApacheMaven/repository/com/vaadin/framework8-migration-tool/8.0-SNAPSHOT/framework8-migration-tool-8.0-SNAPSHOT.jar"
Scanning for compatibility classes for 8.0.0.beta1 version...
Downloading vaadin-compatibility-server 8.0.0.beta1 from Maven to C:\Users\hoehmann/.m2/repository
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NullPointerException
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:361)
        at com.vaadin.framework8.migrate.MavenResolver.resolve(MavenResolver.java:68)
        at com.vaadin.framework8.migrate.VadinJarFinder.download(VadinJarFinder.java:55)
        at com.vaadin.framework8.migrate.VadinJarFinder.lambda$get$0(VadinJarFinder.java:22)
        at java.util.Optional.orElseGet(Unknown Source)
        at com.vaadin.framework8.migrate.VadinJarFinder.get(VadinJarFinder.java:22)
        at com.vaadin.framework8.migrate.Migrate.main(Migrate.java:38)

**Comment by Artur-** [comment]
Sounds a bit like https://bugs.eclipse.org/bugs/show_bug.cgi?id=451566. Is it possible that this simply means that there was a network problem?
